### ISSUE TITLE
Can i user ng-repeat inside hot  hot-column

### ISSUE THREAD

**Issue by vibeesnan** [handsontable/ngHandsontable#50] opened 2015-02-12 09:35 UTC
I need to use dropdown inside hot-column to populate the array of values.
Please help in this case.

**Comment by hardik2792** [comment] 2016-06-11 05:07
@vibeesnan as I have working on ngHandsontable since few days... I found that the using ng-repeat may create issue... you need to populate those values in your controller itself and use it...

**Comment by pepijnolivier** [comment] 2017-03-23 08:45
I can confirm it works, but performance drops majorly. I need to be able to use this on huge tables. Today I'm comparing performance between ngHandsontable and just using the 'raw' handsontable package

**Comment by AMBudnik** [comment] 2018-03-06 10:21
I think that we can close this issue as it hasn't been updated for a long time.

**Closed by AMBudnik** 2018-03-06 10:21 UTC
