### ISSUE TITLE
PublicHooks undefined

### ISSUE THREAD

**Issue by yfarrugia** [handsontable/ngHandsontable#79] opened 2015-06-25 07:56 UTC
Line 169: publicHooks = Object.keys(Handsontable.PluginHooks.hooks)
PublicHooks is undefined and throwing  exception:
TypeError: Cannot read property 'hooks' of undefined

Has anyone encountered this issue ?

Using:
"handsontable": "0.15.0",
"ngHandsontable": "0.5.2"

**Comment by sarahquigley** [comment] 2015-06-25 08:57
I have encountered this issues. It is caused by an incompatibility between the latest ngHandsontable (0.5.2) and handsontable 0.15.0. ngHandsontable 0.5.2 is compatible with handsontable 0.14.1. You could consider downgrading to handsontable 0.14.1, until the ngHandsontable project has been upgraded to have explicit support for handsontable 0.15.0.

**Comment by yfarrugia** [comment] 2015-06-25 15:05
Thank you Sarah, really appreciated, issue #71 is also related to this.

**Comment by victorsosa** [comment] 2015-06-25 15:08
there is a pull request to fix the 0.15 issue; check pull request #75

**Comment by sarahquigley** [comment] 2015-06-25 15:11
Yanika - no problem! Glad I could help. Hopefully this issue will be resolved soon in a new release - pull request https://github.com/handsontable/ngHandsontable/pull/75 should fix it.

**Comment by budnix** [comment] 2015-07-13 18:33
Released in 0.6.0 version.

**Closed by budnix** 2015-07-13 18:34 UTC
Labels: Priority: high
